export const GETQUERYSUCCESS = "GETQUERYSUCCESS";
export const GETRESULTSUCCESS = "GETRESULTSUCCESS";
export const GETQUERYLOADING = "GETQUERYLOADING";
export const GETQUERYFAILIURE = "GETQUERYFAILIURE";